let selected='all', timer;
const $=id=>document.getElementById(id);
let recent=[];
try { const saved=JSON.parse(localStorage.getItem('jaeum-recent')||'[]'); if(Array.isArray(saved)) recent=saved.filter(c=>typeof c==='string'&&groups.some(g=>Array.from(g[3]).includes(c))).slice(0,12); } catch {}
const unicode=c=>'U+'+c.codePointAt(0).toString(16).toUpperCase().padStart(4,'0');
function symbolButton(c,key){const b=document.createElement('button');b.className='symbol';b.textContent=c==='　'?'␣':c;b.title=`${c==='　'?'전각 공백':c} · ${key} + 한자 · ${unicode(c)} · 클릭하여 복사`;b.setAttribute('aria-label',b.title);b.onclick=()=>copy(c,b);return b;}
async function copy(c,b){let ok=false;try{await navigator.clipboard.writeText(c);ok=true;}catch{const t=document.createElement('textarea');t.value=c;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();try{ok=document.execCommand('copy');}catch{}t.remove();}if(!ok){const d=$('fallback');d.querySelector('input').value=c;d.showModal();d.querySelector('input').select();return;}recent=[c,...recent.filter(x=>x!==c)].slice(0,12);try{localStorage.setItem('jaeum-recent',JSON.stringify(recent));}catch{}renderRecent();if(b){b.classList.add('copied');setTimeout(()=>b.classList.remove('copied'),700);}$('toast').textContent=`${c==='　'?'전각 공백':c} 복사했어요`; $('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),2000);}
function renderRecent(){$('recent-wrap').hidden=!recent.length;$('recent').replaceChildren(...recent.map(c=>{const b=document.createElement('button');b.textContent=c==='　'?'␣':c;b.title=`${unicode(c)} 복사`;b.setAttribute('aria-label',`${c==='　'?'전각 공백':c} 다시 복사`);b.onclick=()=>copy(c,b);return b;}));}
function render(){const query=$('search').value.trim().toLowerCase();const matches=groups.filter(g=>selected==='all'||selected===g[0]).map(g=>{const category=[g[0],g[1],g[2]].some(s=>s.toLowerCase().includes(query));const chars=Array.from(g[3]).filter(c=>!query||category||c.toLowerCase().includes(query)||unicode(c).toLowerCase().includes(query));return{g,chars,show:chars.length||(!query&&!g[3])};}).filter(x=>x.show);$('cards').replaceChildren();let total=0;for(const {g,chars} of matches){total+=chars.length;const card=document.createElement('article');card.className='card';const head=document.createElement('div');head.className='card-head';head.innerHTML=`<span class="letter">${g[0]}</span><div><h3>${g[1]}</h3><small>${g[0]} + 한자</small></div><span>${chars.length}개 문자</span>`;card.append(head);const grid=document.createElement('div');grid.className='symbols';grid.append(...chars.map(c=>symbolButton(c,g[0])));card.append(grid);if(!chars.length){const p=document.createElement('p');p.className='no-symbols';p.textContent='ㅉ에는 일반적인 자음 + 한자 특수문자 목록이 없습니다.';card.append(p);}$('cards').append(card);}$('heading').textContent=query?'검색 결과':selected==='all'?'전체 특수문자':`${selected} 특수문자`;$('count').textContent=`${matches.length}개 분류 · ${total}개 문자`;$('empty').hidden=matches.length>0;document.querySelectorAll('nav button').forEach(b=>{const active=b.dataset.key===selected;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});}
for(const [key,label] of [['all','전체 보기'],...groups.map(g=>[g[0],g[1]])]){const b=document.createElement('button');b.dataset.key=key;b.innerHTML=`<span>${key==='all'?'⊞':key}</span>${label}`;b.onclick=()=>{selected=key;render();};$('nav').append(b);}
function reset(){selected='all';$('search').value='';render();}
$('search').addEventListener('input',()=>{selected='all';render();});$('reset').onclick=reset;$('empty-reset').onclick=reset;$('clear').onclick=()=>{recent=[];try{localStorage.removeItem('jaeum-recent');}catch{}renderRecent();};$('fallback').querySelector('button').onclick=()=>$('fallback').close();document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA/.test(e.target.tagName)){e.preventDefault();$('search').focus();}});renderRecent();render();
